### ISSUE TITLE
Add serilization (binary marshal unmarshal) for signature, public key and private key types

### ISSUE THREAD

**Issue by david415** [kasperdi/SPHINCSPLUS-golang#2]
We can't actually use this library in the real world unless we can serialize and deserialize the keys and signature. This is a basic requirement for any cryptography library.

**Comment by david415** [comment]
We could possibly use this CBOR library which is design to deal with "untrusted input":
https://github.com/fxamacker/cbor/

If this path is chosen, (or other similar serialization library that uses golang reflection) then the types that will be serialized are required to have all their struct fields be exported (exported when field name begins with a capital letter). 

We want to be able to take any of the sphincs types, SPHINCS_PK, SPHINCS_SK, SPHINCS_SIG and use cbor.Marshal/Unmarsahl on them:

```
blob, err := cbor.Marshal(myType)
```
```
err := cbor.Unmarshal(byteSlice, myType)
```

whereas currently TreePKAUTH has an unexported field:
https://github.com/kasperdi/SPHINCSPLUS-golang/blob/main/fors/fors.go#L15
```
type TreePKAUTH struct {
	privateKeyValue []byte
	AUTH            []byte
}
```

an alternative to renaming the field to be exported (capitalized first letter) is to create a helper type for use in serialization methods:

```
type treePKAUTHDisk struct {
	PrivateKeyValue []byte
	AUTH            []byte
}
```
and then
```
func (t *TreePKAUTH) MarshalBinary() (data []byte, err error) {
// ...
}

func (t *TreePKAUTH) UnmarshalBinary(data []byte) error {
// ...
}
```

**Comment by david415** [comment]
We also need to write helper functions to create "empty" types. For example if I'm deserializing signature or a public key or a private key we first need to create the type and then call Unmarshal on it:

```
err := cbor.Unmarshal(byteSlice, myType)
```

however in doing so I tried to create the empty signature type like this:

```
sig := &sphincs.SPHINCS_SIG{
			R: []byte{},
			SIG_FORS: &fors.FORSSignature{
				Forspkauth: []*fors.TreePKAUTH{
					&fors.TreePKAUTH{
						PrivateKeyValue: []byte{},
						AUTH:            []byte{},
					},
				},
			},
			SIG_HT: &hypertree.HTSignature{
				XMSSSignatures: []*xmss.XMSSSignature{
					&xmss.XMSSSignature{
						WotsSignature: []byte{},
						AUTH:          []byte{},
					},
				},
			},
```

but unmarshaling data into that empty type does result in a panic. I think it needs the various fields to point to allocated slices of memory of specific sizes.

**Comment by kasperdi** [comment]
I implemented basic serialization of signatures, public keys, and secret keys. The code is in sphincs/serialize.go. Admittedly not the cleanest code, but i will clean it up a bit later. To implement the serialization i had to make WotsSignature in xmss.go and PrivateKeyValue in fors.go public, so CBOR should also be an option for you now.

In terms of your most recent comment, its getting too late, so i will have to look at a later time.

**Comment by david415** [comment]
Thanks! Looks good. Sleep is important too.

**Comment by david415** [comment]
I don't think we need to write functions to create "empty" types from my comment https://github.com/kasperdi/SPHINCSPLUS-golang/issues/2#issuecomment-1275218016

This is because your deserialization functions create the type.

**Comment by kasperdi** [comment]
So it looks like the bug was actually due to a side effect in verify, which modified the public key in some rare instances. It was relatively easy to fix, and your tests pass now. This also explains why my own unit tests for the serialization passed, since these did not attempt to verify.

As a side note I want to mention that version 3.1 specification of SPHINCS+ was released recently. This implementation has still not been updated from version 3.0. As far as I know the only major change was that SHA2-256 was changed for SHA2-512 for the parameter sets with symmetric security level equivalent to 192 and 256 bit keys. This is of course only relevant f or the parameter sets instantiated using SHA2. I want to eventually update this implementation, but it might take a little while. See https://github.com/sphincs/sphincsplus/commit/61cd2695c6f984b4f4d6ed675378ed9a486cbede for more info.

**Comment by david415** [comment]
Yes and apparently they broke it, here's the paper https://eprint.iacr.org/2022/1061
This of course raises many questions like are all params of Sphincs+ broken or just some of them?
Which param is the most conservative? I'll choose that one.

**Comment by kasperdi** [comment]
Closing issue, since serialization of signatures, public keys, and private keys has been implemented.
