### ISSUE TITLE
Unclear license

### ISSUE THREAD

**Issue by wussler** [kasperdi/SPHINCSPLUS-golang#4]
Hi @kasperdi, I'd be interested in using and helping out with this library. What license is it currently under?

It would be cool if you could add a LICENSE.md file so that the documentation can also be [automatically generated](https://pkg.go.dev/license-policy) and found [here](https://pkg.go.dev/github.com/kasperdi/SPHINCSPLUS-golang/sphincs)

Cheers and thanks,
Aron

**Comment by kasperdi** [comment]
Hi, i have added a license now.

**Comment by wussler** [comment]
Thank you very much for the prompt action!
